CREATE DATABASE ProjetoDS_2020;

USE ProjetoDS_2020;

CREATE TABLE Usuario (
idUsuario INT PRIMARY KEY IDENTITY(1,1),
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
userName VARCHAR(100) NOT NULL UNIQUE,
senha VARCHAR(50) NOT NULL,
tipo VARCHAR(20) NOT NULL DEFAULT 'usuario',
ativo VARCHAR(10) NOT NULL DEFAULT 'ativo',
CPF VARCHAR(14) NOT NULL UNIQUE);

select * from Usuario;

